### ISSUE TITLE
How to get voice file path by the EnMicroMsg.db?

### ISSUE THREAD

**Issue by Jiezhi** [danghvu/WeChatRE#1]
I've got the decrypted database,but I can't locate the accurate voice file path.
For example,there is a recored like "351424110614d8a371e2e1b103" in the table voiceinfo,and this file path is stored in "***/voice2/b3/fe/msg_351424110614d8a371e2e1b103.amr".
How can get "b3/fe" from the table?Thanks!

**Comment by ajburley** [comment]
Hi JieZhi,

You need to use MD5 hash to get this. You can use any website, such as onlinemd5.com. For example, on that website you would enter 351424110614d8a371e2e1b103 into the box "Generate the hash of the string you input". Make sure MD5 radio button is checked. Then click "Calculate". You will see the result below: B3FEEF5F63289ED62AB25BC78E922FD8. Now just take characters 1 and 2 and change to lowercase for the first folder (b3) and characters 3 and 4 and change to lowercase for the second folder (fe). Hope that helps.

Adam

**Comment by Jiezhi** [comment]
@ajburley Thanks
